### ISSUE TITLE
Kutty fails to initialize if it cannot add rules to the first stylesheet

### ISSUE THREAD

**Issue by rschroll** [bigskysoftware/kutty#13]
The `addRule` function can fail, and if it does it halts the entire initialization process.  There are at least two ways this can happen:
1. If there are no stylesheets in a document, `document.styleSheets[0]` is `undefined`.
2. If the first stylesheet is provided by a remote server and the proper CORS settings are not set, the Kutty JS is not allowed to access the `cssRules` of that stylesheet.  As an example,

    `<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">`

    will not work, but

    `<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" crossorigin="anonymous">`

    will.

There are a number of ways this could be solved.  Off the top of my head:
1. Kutty could insert its own stylesheet and stick the rules in that.
2. Kutty could catch errors from `addRule`, and log an explanation of what's gone wrong.  People who are not using `kutty-indicator` won't care.
3. This could be dropped from JS, and a CSS file, or even snippet, could be provided for users to include themselves.  While this is a little more work, it would make it easier for users to override the default CSS behavior.

**Comment by chg20** [comment]
OK, we are looking at this in the gitter room right now:

https://gitter.im/intercooler-js/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link

I think that inserting a stand alone sheet is the right thing.  What do you think?

**Comment by rschroll** [comment]
Synchronicity!  I agree that sticking the rules in an arbitrary sheet is probably asking for trouble, even beyond the issues here.  Whether they go into a sheet that Kutty makes automatically, or whether we make the user include it manually, I don't care too much.

**Comment by chg20** [comment]
What do you think about this code:

```javascript
        // insert kutty-indicator css rules
        getDocument().head.insertAdjacentHTML("beforeend",
"<style>\
  .kutty-indicator{opacity:0;transition: opacity 200ms ease-in;}\
  .kutty-request .kutty-indicator{opacity:1}\
  .kutty-request.kutty-indicator{opacity:1}\
</style>");
```

**Comment by chg20** [comment]
I think we need to insert the style sheet early like this (rather than in onLoad) to avoid a flash of unstyled content, right?

**Comment by rschroll** [comment]
Seems good to me.

WRT unstyled content, this may depend on where kutty.js gets included in the document.  With the current code, if I add kutty.js at the end of the document, I can sometimes get the flash.  This might be an argument for a separate CSS file.

**Comment by chg20** [comment]
OK, I am doing the default styling injection, but letting users opt out with a meta configuration.  That preserves the "just works" nature of the default behavior but lets people tweak it if they want a different setup.

**Comment by rschroll** [comment]
Thanks for the quick fix!
