### ISSUE TITLE
Something wrong with CDN version

### ISSUE THREAD

**Issue by jreviews** [bigskysoftware/kutty#2]
The link to add the library in the documentation is broken:

`https://unpkg.com/kutty.org@0.0.1`

And this one has an issue with parameters not being included in POST requests:

`https://unpkg.com/kutty.org@0.0.1-alpha.2/dist/kutty.min.js`

However, the version loaded at kutty.org works correctly.

Thanks!

**Comment by chg20** [comment]
:)  I haven't done an official release yet.  For right now you can grab it out of master if you'd like.
