### ISSUE TITLE
oob swap not working correctly with more then one swap

### ISSUE THREAD

**Issue by jsantari** [bigskysoftware/kutty#4]
I am trying a simple kutty test for oob. The rendered html / dom does not come out correctly with more then one oob. You can view the test page here: http://kutty.nwcomp.com/ - If you click the heading the content is retrieved (see response) and the first oob swap works fine the second one does not.

**Comment by chg20** [comment]
Can you create a regression test in /test/core/regressions.js?

**Comment by jsantari** [comment]
Not familiar with doing that.

**Comment by chg20** [comment]
Check out these tests:

https://github.com/bigskysoftware/kutty/blob/master/test/attributes/kt-swap-oob.js

Basically you set up a mock server response or two, create an html fragment using `make` and then click it and assert stuff about the response.  

Of if you like you can just post the stuff into this ticket and I'll do it.  But I'd love to test the regression contribution process :)

**Comment by jsantari** [comment]
Sorry - I don't have time to experiment with that. I've provided a link to the two page simple example.
First page content inside body is:
`<h1 kt-get='index2a.php' kt-target="#page2" kt-trigger='click'>Kutty CLICK ME</h1>

<div id="page2" ></div>
<div id="message"></div>
<div id="message2"></div>`

Index2a.php contains the following html for the response:
`<div id='message' kt-swap-oob='true'><h3>I came from message oob swap I should be second</h3></div>
<div id='message2' kt-swap-oob='true'><h4>I came from a message2 oob swap I should be third  but I am in the wrong spot</h4></div>
<h3>I'm page2 content (non-swap) I should be first</h3>`

**Comment by chg20** [comment]
Thanks for the report, I created a regression test based on your code:

https://github.com/bigskysoftware/kutty/blob/d4b4d462ab577a8e481e07e540bb3bc4343476c6/test/core/regressions.js#L21

And an attribute test that simplifies it:

https://github.com/bigskysoftware/kutty/blob/d4b4d462ab577a8e481e07e540bb3bc4343476c6/test/attributes/kt-swap-oob.js#L21

Both on line 21?  Crazy.

Anyway, you can grab the latest src from the 'dev' branch or wait until next friday when I'm going to push 0.1.0
